export const environment = {
  MESSAGE: '[DEFAULT MESSAGE]',
  MY_NODE_NAME: '[DEFAULT MY_NODE_NAME]',
  MY_POD_NAME: '[DEFAULT MY_POD_NAME]',
  MY_POD_NAMESPACE: '[DEFAULT MY_POD_NAMESPACE]',
  MY_POD_IP: '[DEFAULT MY_POD_IP]',
  MY_POD_SERVICE_ACCOUNT: '[DEFAULT MY_POD_SERVICE_ACCOUNT]'
}
